
is_gui          = false
build_platform  = ''

plugins_auto_update    = false
log_plugins_to_stdout  = true

[version]
major         = 1
minor         = 4
patch         = 0
list          = [ 1, 4, 0 ]
beta          = true
indev         = true
full_version  = "1.4.0"
