# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\Projects\Python\EasyTl\easytl-gui\ui\instanceRollingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instanceRollingWidget(object):
    def setupUi(self, instanceRollingWidget):
        instanceRollingWidget.setObjectName("instanceRollingWidget")
        instanceRollingWidget.resize(650, 332)
        instanceRollingWidget.setMinimumSize(QtCore.QSize(650, 332))
        instanceRollingWidget.setMaximumSize(QtCore.QSize(650, 332))
        instanceRollingWidget.setStyleSheet("")
        self.tabsTW = QtWidgets.QTabWidget(instanceRollingWidget)
        self.tabsTW.setGeometry(QtCore.QRect(0, 0, 651, 331))
        self.tabsTW.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabsTW.setObjectName("tabsTW")
        self.statusTab = QtWidgets.QWidget()
        self.statusTab.setObjectName("statusTab")
        self.groupBox = QtWidgets.QGroupBox(self.statusTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 631, 291))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 171, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.startBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startBtn.setGeometry(QtCore.QRect(10, 40, 151, 31))
        self.startBtn.setObjectName("startBtn")
        self.stopBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.stopBtn.setGeometry(QtCore.QRect(10, 80, 151, 31))
        self.stopBtn.setObjectName("stopBtn")
        self.restartBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.restartBtn.setGeometry(QtCore.QRect(10, 120, 151, 31))
        self.restartBtn.setObjectName("restartBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 171, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.runningRatio = QtWidgets.QRadioButton(self.groupBox_3)
        self.runningRatio.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.runningRatio.setObjectName("runningRatio")
        self.logsEditStatus = QtWidgets.QTextEdit(self.groupBox)
        self.logsEditStatus.setGeometry(QtCore.QRect(190, 20, 431, 261))
        self.logsEditStatus.setReadOnly(True)
        self.logsEditStatus.setObjectName("logsEditStatus")
        self.tabsTW.addTab(self.statusTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.debugTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 621, 291))
        self.groupBox_4.setObjectName("groupBox_4")
        self.runCodeBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.runCodeBtn.setGeometry(QtCore.QRect(520, 260, 91, 21))
        self.runCodeBtn.setObjectName("runCodeBtn")
        self.loadScriptBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.loadScriptBtn.setGeometry(QtCore.QRect(490, 10, 121, 31))
        self.loadScriptBtn.setObjectName("loadScriptBtn")
        self.codeLine = QtWidgets.QLineEdit(self.groupBox_4)
        self.codeLine.setGeometry(QtCore.QRect(10, 260, 501, 21))
        self.codeLine.setObjectName("codeLine")
        self.logsEditDebug = QtWidgets.QTextEdit(self.groupBox_4)
        self.logsEditDebug.setGeometry(QtCore.QRect(10, 50, 601, 201))
        self.logsEditDebug.setReadOnly(True)
        self.logsEditDebug.setObjectName("logsEditDebug")
        self.tabsTW.addTab(self.debugTab, "")

        self.retranslateUi(instanceRollingWidget)
        self.tabsTW.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(instanceRollingWidget)

    def retranslateUi(self, instanceRollingWidget):
        _translate = QtCore.QCoreApplication.translate
        instanceRollingWidget.setWindowTitle(_translate("instanceRollingWidget", "Form"))
        self.groupBox.setTitle(_translate("instanceRollingWidget", "Instance"))
        self.groupBox_2.setTitle(_translate("instanceRollingWidget", "CONTROL"))
        self.startBtn.setText(_translate("instanceRollingWidget", "START"))
        self.stopBtn.setText(_translate("instanceRollingWidget", "STOP"))
        self.restartBtn.setText(_translate("instanceRollingWidget", "RESTART"))
        self.groupBox_3.setTitle(_translate("instanceRollingWidget", "STATUS"))
        self.runningRatio.setText(_translate("instanceRollingWidget", "IS RUNNING"))
        self.tabsTW.setTabText(self.tabsTW.indexOf(self.statusTab), _translate("instanceRollingWidget", "STATUS"))
        self.groupBox_4.setTitle(_translate("instanceRollingWidget", "DEBUG"))
        self.runCodeBtn.setText(_translate("instanceRollingWidget", "RUN"))
        self.loadScriptBtn.setText(_translate("instanceRollingWidget", "LOAD SCRIPT"))
        self.tabsTW.setTabText(self.tabsTW.indexOf(self.debugTab), _translate("instanceRollingWidget", "DEBUG"))
