# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\Projects\Python\EasyTl\easytl-gui\ui\instanceRollingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instanceRollingWidget(object):
    def setupUi(self, instanceRollingWidget):
        instanceRollingWidget.setObjectName("instanceRollingWidget")
        instanceRollingWidget.resize(650, 312)
        instanceRollingWidget.setMinimumSize(QtCore.QSize(650, 312))
        instanceRollingWidget.setMaximumSize(QtCore.QSize(650, 312))
        self.tabsTW = QtWidgets.QTabWidget(instanceRollingWidget)
        self.tabsTW.setGeometry(QtCore.QRect(0, 0, 651, 311))
        self.tabsTW.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabsTW.setObjectName("tabsTW")
        self.statusTab = QtWidgets.QWidget()
        self.statusTab.setObjectName("statusTab")
        self.groupBox = QtWidgets.QGroupBox(self.statusTab)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 611, 251))
        self.groupBox.setObjectName("groupBox")
        self.runningRatio = QtWidgets.QRadioButton(self.groupBox)
        self.runningRatio.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.runningRatio.setObjectName("runningRatio")
        self.logsBtn = QtWidgets.QPushButton(self.groupBox)
        self.logsBtn.setGeometry(QtCore.QRect(450, 210, 151, 31))
        self.logsBtn.setObjectName("logsBtn")
        self.restartBtn = QtWidgets.QPushButton(self.groupBox)
        self.restartBtn.setGeometry(QtCore.QRect(450, 172, 151, 31))
        self.restartBtn.setObjectName("restartBtn")
        self.stopBtn = QtWidgets.QPushButton(self.groupBox)
        self.stopBtn.setGeometry(QtCore.QRect(450, 130, 151, 31))
        self.stopBtn.setObjectName("stopBtn")
        self.startBtn = QtWidgets.QPushButton(self.groupBox)
        self.startBtn.setGeometry(QtCore.QRect(450, 90, 151, 31))
        self.startBtn.setObjectName("startBtn")
        self.tabsTW.addTab(self.statusTab, "")

        self.retranslateUi(instanceRollingWidget)
        self.tabsTW.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(instanceRollingWidget)

    def retranslateUi(self, instanceRollingWidget):
        _translate = QtCore.QCoreApplication.translate
        instanceRollingWidget.setWindowTitle(_translate("instanceRollingWidget", "Form"))
        self.groupBox.setTitle(_translate("instanceRollingWidget", "Instance"))
        self.runningRatio.setText(_translate("instanceRollingWidget", "IS RUNNING"))
        self.logsBtn.setText(_translate("instanceRollingWidget", "LOGS"))
        self.restartBtn.setText(_translate("instanceRollingWidget", "RESTART"))
        self.stopBtn.setText(_translate("instanceRollingWidget", "STOP"))
        self.startBtn.setText(_translate("instanceRollingWidget", "START"))
        self.tabsTW.setTabText(self.tabsTW.indexOf(self.statusTab), _translate("instanceRollingWidget", "STATUS"))
