
prefixes = [ "easy", "ez" ]                    # Prefixes of the EasyTl
error_notify = "⚠️⛔️ Error was occurred {0}"  # Any error will formatted to this string

[pluginapi]
send_request_error = "while sending a check request of plugin {0}"
requirements_error = "while installing the requirements for plugin {0}"
plugin_execution_error = "while executing plugin {0}"

update_notify = "Plugin {0} has been updated!"
changelog_notify = "v{0} changelog:\n\n{1}"

# Commands of the Core plugin

[command.stop]
names = [ "stop" ]
stop_notify = "userbot is being stop"

[command.restart]
names = [ "restart" ]
restart_notify = "userbot is being restart"
restarted_notify = "userbot is restarted!"

[command.pass]
names = [ "pass" ]
