
prefixes = [ "easy", "ez", "изи" ]           # Префиксы для EasyT;
error_notify = "⚠️⛔️ Произошла ошибка {0}"  # Любая ошибка будет форматирована под эту строку

[pluginapi]
send_request_error = "во время отправки запроса проверки на плагин {0}"
download_languages_error = "во время скачивания переводов плагина {0}"
requirements_error = "во время установки зависимостей плагина {0}"
plugin_execution_error = "во время запуска плагина {0}"

update_notify = "Плагин {0} был обновлён!"
changelog_notify = "v{0} список изменений:\n\n{1}"

[instance]
telegram_get_number = "Введите ваш номер телефона для авторизации в телеграмм: "
telegram_get_code = "Введите полученный код: "
telegram_get_password = "Введите ваш пароль для доступа к аккаунту: "

# Команды плагина Core

[command.stop]
names = [ "stop", "стоп" ]
stop_notify = "юзербот будет остановлен"

[command.restart]
names = [ "restart", "рестарт" ]
restart_notify = "юзербот будет перезапущен"
restarted_notify = "юизербот перезапущен!"

[command.clear-cache]
names = [ "clearcache", "clrcache", "очисткэш" ]
cleaned_message = "Кэш был очищен!"

[command.calc]
names = [ "calculator", "calc", "обчисл" ]
output_message = "**КАЛЬКУЛЯТОР** : `{0}`"

[command.pass]
names = [ "pass", "пасс", "Ukraine_is_win" ]
