
[command.vtt]
names = [ "voicetotext", "vtt", "totext", "втекст", "дотексту" ]
no_media_message = "Повідомлення не має медіа контенту!"
isnt_audio_message = "Це не є аудіо контентом!"
success_message = "Google STT:\n{0}"
no_reply_to_message = "Ви мали були відповісти на аудіо чи др. контент!"