
build_platform  = ''

plugins_auto_update    = false

[version]
major         = 1
minor         = 4
patch         = 0
subpatch      = 0
list          = [ 1, 4, 0 ]
beta          = false
indev         = true
full_version  = "1.4.0"
