
build_platform  = ''

plugins_auto_update    = false

[version]
major         = 1
minor         = 4
patch         = 1
subpatch      = 1
list          = [ 1, 4, 1 ]
beta          = false
indev         = true
full_version  = "1.4.1.1-indev"